In [1]:
# Python has built-in 'lists':
x = [1,2,3]
print(x)

[1, 2, 3]


In [2]:
# But they don't work as you would expect
x*2

[1, 2, 3, 1, 2, 3]

In [3]:
# And most vector-operations fail
x*2.3

TypeError: can't multiply sequence by non-int of type 'float'

In [4]:
# Numpy: The module for scientific computing with python
import numpy as np
x = np.array([1,2,3])
print(x)

[1 2 3]


In [5]:
x.dtype

dtype('int64')

In [6]:
# Now you can manipulate your array in every way thinkable:
x*2.3

array([ 2.3,  4.6,  6.9])

In [7]:
x/100.

array([ 0.01,  0.02,  0.03])

In [8]:
# numpy arrays can be combined with lists
y = [10.,10,10]
x+y

array([ 11.,  12.,  13.])

In [9]:
x/y

array([ 0.1,  0.2,  0.3])

In [10]:
x**2

array([1, 4, 9])

In [12]:
# The dot (or scalar) or cross product
np.cross(x,y)

array([-10.,  20., -10.])

In [13]:
# Setting up a matrix
z = np.array([[2,3,5],[4,3,7],[9,4,5]])
print(z)

[[2 3 5]
 [4 3 7]
 [9 4 5]]


In [14]:
z*z

array([[ 4,  9, 25],
       [16,  9, 49],
       [81, 16, 25]])

In [15]:
k = np.array([3,2,1])
np.dot(z,k)

array([17, 25, 40])

In [16]:
# Note: np.dot(z,k) is not the same as z*k:
z*k

array([[ 6,  6,  5],
       [12,  6,  7],
       [27,  8,  5]])

In [17]:
# How to access an element in an array:
k

array([3, 2, 1])

In [18]:
k[0]

3

In [19]:
# Normal parentheses are for callable functions only:
k(0)

TypeError: 'numpy.ndarray' object is not callable

In [23]:
# A dictionary can contain a combination of lists and arrays:
x = {'a':[1,2,3],'z':z}

In [24]:
x['a']

[1, 2, 3]

In [25]:
x['z']

array([[2, 3, 5],
       [4, 3, 7],
       [9, 4, 5]])